### ISSUE TITLE
Call to undefined method Monolog\Logger::addInfo()

### ISSUE THREAD

**Issue by vivianequinaia** [arquivei/events-sender#22]
No arquivo `vendor/arquivei/events-sender/src/Exporters/File.php`
Temos a seguinte chamada
![image](https://github.com/user-attachments/assets/a42fb971-d6cc-4bfe-9114-53f8e2306e2e)
Mas verificando o arquivo `vendor/monolog/monolog/src/Monolog/Logger.php`
Esse método não existe mais.
Sugiro Utilizar o método info() ou addRecord()
![image](https://github.com/user-attachments/assets/76c2b8a7-a89b-450b-a3d8-4ba2cf2590e1)

**Comment by filipebafica** [comment]
@vivianequinaia obrigado pelo envio. Você pode seguir com a abertura de uma pull request?

**Comment by vivianequinaia** [comment]
> @vivianequinaia obrigado pelo envio. Você pode seguir com a abertura de uma pull request?

Abrirei a PR

**Comment by vivianequinaia** [comment]
@filipebafica 
ERROR: Permission to arquivei/events-sender.git denied to vivianequinaia.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by filipebafica** [comment]
@vivianequinaia PR mergeada. Obrigado.
